using ConvolutionInterpolations
using Test

@testset "ConvolutionInterpolations.jl" begin
    include("test_constructors.jl")
    include("test_uniform_interpolation.jl")
    include("test_uniform_derivatives.jl")
    include("test_uniform_convergence.jl")
    include("test_uniform_lazy.jl")
    include("test_nonuniform_interpolation.jl")
    include("test_nonuniform_derivatives.jl")
    include("test_nonuniform_convergence.jl")
    include("test_nonuniform_perdim_derivatives.jl")
    include("test_nonuniform_perdim_kernels.jl")
    include("test_nonuniform_a0_a1.jl")
    include("test_nonuniform_lazy.jl")
    include("test_antiderivative.jl")
    include("test_perdim_derivatives.jl")
    include("test_mixed_integral_1D_2D.jl")
    include("test_mixed_integral_3D_4D.jl")
    include("test_mixed_integral_5D.jl")
    include("test_perdim_kernel_derivatives.jl")
    include("test_boundary_condition.jl")
    include("test_extrapolation.jl")
    include("test_subgrid_downgrade.jl")
    include("test_gaussian.jl")
    include("test_bigfloat_precision.jl")
    include("test_allocations.jl")
    include("test_resample.jl")
end