include("basic_accessors.jl")
include("convolution_interpolation_constructor.jl")
include("convolution_interpolation_function.jl")
include("extend_knots.jl")
include("extend_vector.jl")
include("fast_convolution_interpolation_constructor.jl")
include("indexing_and_calling.jl")