include("autocor_coefs.jl")
include("boundary_coefs.jl")
include("create_convolutional_coefs.jl")
include("linear_predict.jl")
include("autocorrelation.jl")
include("detect_boundary_signal_fast.jl")
include("periodic_boundary.jl")